# Упражнения с NumPy 

Давайте проверим ваши знания. Мы начнем с нескольких простых задач, а затем вам будут заданы несколько более сложных вопросов.

Важно! Код, который вы напишите в этом ноутбуке, вам нужно сохранить в виде файла c именем "Numpy_solutions.ipynb" в вашем личном репозитории на GitHub.

#### 1. Импорт NumPy 

In [18]:
import numpy as np

#### 2. Создать массив из 10 нулей

In [19]:
import numpy as np

array_of_zeros = np.zeros(10)
print(array_of_zeros)



[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [20]:
# не пишите код в этой ячейке

#### 3. Создать массив из 10 единиц

In [21]:
import numpy as np

array_of_ones = np.ones(10)
print(array_of_ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [22]:
# не пишите код в этой ячейке

#### 4. Создать массив из  10 пятерок

In [23]:
import numpy as np

array_of_fives = np.full(10, 5)
print(array_of_fives)

[5 5 5 5 5 5 5 5 5 5]


In [24]:
# не пишите код в этой ячейке

#### 5. Создать массив из целых чисел от 10 до 50

In [25]:
import numpy as np

array_from_10_to_50 = np.arange(10, 51)
print(array_from_10_to_50)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [26]:
# не пишите код в этой ячейке

#### 6. Создать массив из четных числел от 10 до 50

In [27]:
import numpy as np

array_of_even_numbers = np.arange(10, 51, 2)
print(array_of_even_numbers)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [28]:
# не пишите код в этой ячейке

#### 7. Создать матрицу 3х3 с числами от 0 до 8

In [29]:
import numpy as np

array_0_to_8 = np.arange(9)
matrix_3x3 = array_0_to_8.reshape(3, 3)

print(matrix_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [30]:
# не пишите код в этой ячейке

#### 8. Создать единичную матрицу 3x3 

In [31]:
import numpy as np

identity_matrix = np.eye(3)

print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
# не пишите код в этой ячейке

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 9. Используйте NumPy для генерации случайного числа от 0 до 1
<br>ПРИМЕЧАНИЕ. Значение вашего результата должно отличаться от приведенного ниже.

In [40]:
import numpy as np

random_number = np.random.rand()
print(random_number)

0.6166245556688309


In [32]:
# не пишите код в этой ячейке

#### Используйте NumPy для генерации массива из 25 случайных чисел, взятых из стандартного нормального распределения
<br>ПРИМЕЧАНИЕ. Значение вашего результата должно отличаться от приведенного ниже.

In [42]:
random_array = np.random.rand(25)
print(random_array)

[0.84368762 0.53732495 0.70418239 0.49360969 0.88123638 0.45916043
 0.6714499  0.24557916 0.05863605 0.12756428 0.98541388 0.49489446
 0.44461695 0.39383534 0.80701824 0.01361171 0.26019091 0.55141527
 0.57840783 0.67976239 0.07473774 0.81341448 0.2608222  0.51999187
 0.16238886]


In [41]:
# не пишите код в этой ячейке

#### 11. Создайте следующую матрицу:

In [44]:
import numpy as np

matrix = np.arange(1, 101).reshape(10, 10) / 100
print(matrix)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [43]:
# не пишите код в этой ячейке

#### 12. Создайте массив из 20 линейно расположенных точек между 0 и 1:

In [45]:
import numpy as np

array_of_points = np.linspace(0, 1, 20)
print(array_of_points)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [12]:
# не пишите код в этой ячейке

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy индексация и выборка

Дана стартовая матрица (обязательно запустите ячейку ниже!). Вам необходимо повторить выходные результаты матрицы:

In [47]:
# это наша стартовая матрица
mat = np.arange(1,26).reshape(5,5)
mat

new_mat = mat.copy() 
new_mat = new_mat.reshape(5, 5)  
print("\nПовторение выходных результатов:")
print(new_mat)


Повторение выходных результатов:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


#### 13. Напишите код, который воспроизводит вывод, показанный ниже.


In [74]:
import numpy as np

mat = np.arange(1, 26).reshape(5, 5)

output_mat = mat[1:, 1:]
output_str = np.array2string(output_mat, separator=',', formatter={'int': lambda x: f'{x}'})
output_str = output_str.replace('[7,8,9,10]', '')
print(output_str)

[,
 [12,13,14,15],
 [17,18,19,20],
 [22,23,24,25]]


In [14]:
# не пишите код в этой ячейке

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

#### 14. Напишите код, который воспроизводит вывод, показанный ниже.

In [70]:
import numpy as np

mat = np.arange(1, 26).reshape(5, 5)


number_20 = mat[3, 4]
print(number_20)


20


In [15]:
# не пишите код в этой ячейке

20

#### 15. Напишите код, который воспроизводит вывод, показанный ниже.

In [79]:
import numpy as np


mat = np.arange(1, 26).reshape(5, 5)
output_mat = mat[0:3:1, 1:2]
print(output_mat)

[[ 2]
 [ 7]
 [12]]


In [16]:
# не пишите код в этой ячейке

array([[ 2],
       [ 7],
       [12]])

#### 16. Напишите код, который воспроизводит вывод, показанный ниже.

In [80]:
import numpy as np


mat = np.arange(1, 26).reshape(5, 5)
output_mat = mat[4, :]
print(output_mat)

[21 22 23 24 25]


In [17]:
# не пишите код в этой ячейке

array([21, 22, 23, 24, 25])

#### 17. Напишите код, который воспроизводит вывод, показанный ниже.

In [81]:
import numpy as np


mat = np.arange(1, 26).reshape(5, 5)
output_mat = mat[3:5, :]
print(output_mat)

[[16 17 18 19 20]
 [21 22 23 24 25]]


In [18]:
# не пишите код в этой ячейке

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## Операции NumPy 

#### 18. Получить сумму всех значений в матрице mat

In [82]:
import numpy as np

mat = np.arange(1, 26).reshape(5, 5)
sum_of_values = mat.sum()
print(sum_of_values)

325


In [19]:
# не пишите код в этой ячейке

325

#### 19. Получить стандартное отклонение в матрице mat

In [83]:
import numpy as np


mat = np.arange(1, 26).reshape(5, 5)
std_deviation = mat.std()
print( std_deviation)

7.211102550927978


In [20]:
# не пишите код в этой ячейке

7.211102550927978

#### 20. Получить сумму значений в колонках в матрице mat

In [84]:
import numpy as np


mat = np.arange(1, 26).reshape(5, 5)
column_sums = np.sum(mat, axis=0)
print(column_sums)


[55 60 65 70 75]


In [21]:
# не пишите код в этой ячейке

array([55, 60, 65, 70, 75])

## Бонусный вопрос

Есть ли способ гарантировать, что мы всегда получим одинаковые случайные числа?